
trigger:
- main

pool: default

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    backendServiceArm: 'az-ado-connection'
    backendAzureRmResourceGroupName: 'rgkulvinder'
    backendAzureRmStorageAccountName: 'stgkulvinder1'
    backendAzureRmContainerName: 'container1'
    backendAzureRmKey: 'dev.terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
    environmentServiceNameAzureRM: 'az-ado-connection'
